# Generated by Django 4.2.3 on 2026-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
