# Generated by Django 4.2.3 on 2026-02-11 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categoria', models.CharField(choices=[('MOUNTAIN', 'Mountain'), ('ROAD', 'Road'), ('ROAD', 'Road'), ('GRAVEL', 'Gravel'), ('VESTUARIO', 'Vestuario')], default='MOUNTAIN', max_length=100)),
                ('cor', models.CharField(max_length=40)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ano', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d')),
                ('publicada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
