# Generated by Django 4.2.3 on 2026-02-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('MOUNTAIN', 'Mountain'), ('ROAD', 'Road'), ('GRAVEL', 'Gravel'), ('VESTUARIO', 'Vestuario')], default='MOUNTAIN', max_length=100),
        ),
    ]
